print("Hello,How are you?")
city=input("What city are you in?")
print(city)
age=input("How old are you?")
print(age)
email=input("What is your email address?")
print(email)
phone=input("What is your phone number?")
print(phone)
